### ISSUE TITLE
invalid payload: json: unknown field "aws_access_key_id" 

### ISSUE THREAD

**Issue by troykinsella** [concourse/registry-image-resource#126]
I'm trying to push an image built from a custom task script to an ECR repository with the following pipeline configuration:

```
# no resource_types entry for registry-image; using built-in.

resources:
- name: foo
  type: registry-image
  source:
    repository: category/my-ecr-image-name
    aws_access_key_id: ((aws_access_key_id))
    aws_secret_access_key: ((aws_secret_access_key))
    tag: something

jobs:
- name: publish
  plan:
  - task: build foo which produces foo-image volume
     ...
  - put: foo
    params:
      image: foo-image
```

The `put` step then fails with:
```
ERRO[0000] invalid payload: json: unknown field "aws_access_key_id" 
```

This doesn't immediately make sense to me as `aws_access_key_id` is a documented `source` attribute, and I can see that the Go struct defines it: https://github.com/concourse/registry-image-resource/blob/master/types.go#L31

What might I be doing wrong?

Concourse version: 5.8.0

**Comment by fenech** [comment]
I was having the same issue until I switched to the `dev` tag of the resource in my pipeline:

```yaml
resource_types:
  - name: registry-image
    type: registry-image
    source:
      repository: concourse/registry-image-resource
      tag: dev
```
I didn't look into which version of the resource was being used by default, but the latest "release" of this repo is from back in November, so it's likely to be missing things that are in master.
