### ISSUE TITLE
check failed: get remote image: unsupported status code 405 

### ISSUE THREAD

**Issue by radoslav-tomov** [concourse/registry-image-resource#138]
I've stumbled on this very misleading error message when I'm trying to use a registry-image resource to run a task with a specific docker image.

![error](https://i.ibb.co/P4xDNcc/Screenshot-2020-03-26-at-9-59-13.png)

After some playing around with it, I found out, that this happens when the credentials are incorrect and the basic authentication fails.

Here is a sample pipeline, which can be used to reproduce it

```
---
jobs:
  - name: job-hello-world
    public: true
    plan:
      - task: hello-world
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: weberstephanhd/iacbox22
              tag: v280
              username: fake-user
              password: fake-password
          run:
            path: echo
            args: [hello world]
```
I've reproduced it with  registry-image-resource packed in Concourse 5.8.0.

Ideally, the error message should be  401 Unauthorized.
