### ISSUE TITLE
Make it easier to push semver tags

### ISSUE THREAD

**Issue by vito** [concourse/registry-image-resource#15]
This would be a nice sugar on top of `additional_tags` - Docker has a pretty strong convention of pushing a version like `1.2.3` under tags `1`, `1.2`, and `1.2.3` (assuming it's the latest release):

```yaml
put: my-image
params:
  semver_tags: version/version
```

Might want to make the level configurable; if it's a patch for an older version it makes sense to push `1.2` and `1.2.3` but not `1`:

```yaml
put: my-image
params:
  semver_minor_tags: version/version
```

(just a quick mockup, there may be a more intuitive way to configure this)
