### ISSUE TITLE
Custom tag | Question

### ISSUE THREAD

**Issue by demamoh** [concourse/registry-image-resource#17]
Hello,

I wanted to ask how to go about a particular use-case which is tagging and image with a custom tag other than `latest` maybe even generate a unique build number? After doing that, then fetching that new tag, and passing it to another resource's put like linkyard's helm resource.

**Comment by vito** [comment]
This is supported via `additional_tags`:

https://github.com/concourse/registry-image-resource#parameters-1

**Comment by roshankadasani** [comment]
@vito when using `additional_tags` for put the `latest`  tag along with the other tags is being pushed. Can we disable the `latest` tag push? Can we have something similar to `tag_file` from concourse docker-image https://github.com/concourse/docker-image-resource#parameters-1?

```
- put: docker-image
    params: 
      image: image/image.tar
      additional_tags: version/number
```
