### ISSUE TITLE
Get step fails with images from old schema version

### ISSUE THREAD

**Issue by cirocosta** [concourse/registry-image-resource#19]
Hey,

As noticed by Trevor in Discord (sorry, I don't know how to link to a message there), old images like `tutum/hello-world` and `tutum/curl` fail to be fetched by `registry-image` when performing being `get`ed. 

That seems very related to the fact that these images use an older schema version (although that's detectable).

Using the following snippet (click to expand), we can see the different schema versions:

<details>
<summary> snippet </summary>
<pre>
#!/bin/bash

set -o errexit

main() {
  check_args "$@"

  local image=$1
  local tag=$2
  local token=$(get_token $image)

  echo "$(get_tag $image $tag $token)"
}

get_token() {
  local image=$1

  echo "Retrieving Docker Hub token.
    IMAGE: $image
  " >&2

  curl \
    --silent \
    "https://auth.docker.io/token?scope=repository:$image:pull&service=registry.docker.io" \
    | jq -r '.token'
}

get_tag() {
  local image=$1
  local tag=$2
  local token=$3

  echo "Retrieving tag config.
    IMAGE:  $image
    TAG:    $tag
    TOKEN:  $token
  " >&2

  curl \
    --silent \
    --header "Accept: application/vnd.docker.distribution.manifest.v2+json" \
    --header "Authorization: Bearer $token" \
    "https://registry-1.docker.io/v2/$image/manifests/$tag" \
    | jq -r '.'
}

check_args() {
  if (($# != 2)); then
    echo "Error:
    Two arguments must be provided - $# provided.
  
    Usage:
      $0 <image> <tag>
      
Aborting."
    exit 1
  fi
}

main "$@"
</pre>
</details>

<br />

```sh
./get-tag.sh concourse/concourse latest | grep schema
  "schemaVersion": 2,

./get-tag.sh tutum/hello-world latest | grep schema
  "schemaVersion": 1,
```

To reproduce:

```yaml
resources:
  - name: image-docker
    type: docker-image
    source:
      repository: tutum/hello-world

  - name: image-registry
    type: registry-image
    source:
      repository: tutum/hello-world

jobs:
  - name: test
    plan:
      - aggregate:
        - get: image-docker
        - get: image-registry
```

<img width="955" alt="Screen Shot 2019-03-11 at 9 12 03 AM" src="https://user-images.githubusercontent.com/3574444/54126373-c6950880-43dd-11e9-9315-9cf54bbb7b7a.png">
