### ISSUE TITLE
`skip_download` skips tag and digest files creation

### ISSUE THREAD

**Issue by vlfig** [concourse/registry-image-resource#227]
#92 was important and welcome but now if we don't care to download the image we also cannot read `./tag` or `./digest`. This is useful to have determinism downstream (what was built is what the concourse resource page says).

Admittedly my use case is due to vito/oci-build-task#1 therefore hopefully transient, but I expect there to be other situations where we need more than "just trigger" and actually need an exact digest of the image.

**Comment by allan-degnan-rft** [comment]
Same.  Tags are often mutable so I'd rather feed the digest into a docker deploy.  Sadly this means I need to download the image unnecessarily between jobs.

**Comment by techgnosis** [comment]
This is unfortunate. The main reason I wanted to migrate to registry-image-resource was that I hoped it would let me download the tag and digest without downloading the whole image. That's my biggest problem at the moment. I download the image just to get the digest which is a big waste of resources.

**Comment by vito** [comment]
I ended up fixing this as part of #214, so it shouldn't be broken much longer. If someone wants to pull that fix out into a separate PR they're more than welcome to!

**Comment by alexandreroman** [comment]
Please merge the tag/digest creation code to master. I was expecting to use `registry-image-resource` instead of `docker-image-resource`, but having to download full image to get the image tag only is a waste of resources.

**Comment by f0o** [comment]
I'm also facing this issue. Is it resolved by swapping registry-image-resource with docker-image-resource?

I've lost the overview which of the two resources is the preferred one

**Comment by vito** [comment]
This is fixed in v1.0.0 of the resource now that #214 is merged. Concourse v7 will include it - if you need it sooner, feel free to configure it in your pipeline:

```yaml
resource_types:
- name: registry-image
  type: registry-image # use the old version one last time
  source:
    repository: concourse/registry-image
    tag: 1
```

@f0o This is the preferred resource type, so it'd probably be better to roll forward to v1.0 rather than switch to `docker-image`.

**Comment by akshaymankar** [comment]
The config is slightly wrong, for anybody else who wants to copy-pasta the config:

```yaml
resource_types:
- name: registry-image
  type: registry-image # use the old version one last time
  source:
    repository: concourse/registry-image-resource
    tag: 1
```
