### ISSUE TITLE
Pulling an using an image which symlinks /sys causes an error

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [concourse/registry-image-resource#235]
# Context
The platform automation image @ [Platform Automation toolkit](https://network.pivotal.io/products/platform-automation/) symlnks /sys and when pulled down and used as a task image, it fails with 

[PLACE HOLDER IMAGE]

## Steps
1. Deploy current leased Concourse v6.4.1
1. Setup the pipeline
    ```
    jobs:
    - name: test-registry-image-0.11.1
      plan:
      - get: pai-registry-image-0.11.1
      - task: test
        image: pai-registry-image-0.11.1
        config:
          platform: linux
          run:
            args:
            - -c
            - |
              #!/bin/bash
              ls -la /
            path: sh
    
    - name: test-registry-image-0.8.2
      plan:
      - get: pai-registry-image-0.8.2
      - task: test
        image: pai-registry-image-0.8.2
        config:
          platform: linux
          run:
            args:
            - -c
            - |
              #!/bin/bash
              ls -la /
            path: sh
    
    - name: test-docker-image
      plan:
      - get: pai-docker-image
      - task: test
        config:
          platform: linux
          run:
            args:
            - -c
            - |
              #!/bin/bash
              ls -la /
            path: sh
        image: pai-docker-image
    
    resource_types:
    - name: ri-11
      type: registry-image
      source:
        repository: concourse/registry-image-resource
        tag: 0.11.1
    - name: ri-8
      type: registry-image
      source:
        repository: concourse/registry-image-resource
        tag: 0.8.2
    
    resources:
    - name: pai-docker-image
      type: docker-image
      source:
        repository: xtremesameer/pai
    
    - name: pai-registry-image-0.11.1
      type: ri-11
      source:
        repository: xtremesameer/pai
    
    - name: pai-registry-image-0.8.2
      type: ri-8
      source:
        repository: xtremesameer/pai

    ```
1. Trigger each job and...

### Expected
All jobs pass.

### Actual
both jobs that use the `registry-image` resource fail. The `docker-image` resource passes.

---

These are the test cases we ran through:
```
---
Concourse 6.4.1
test-registry-image (0.11.1): failed
test-docker-image: passed
side-note: registry-image was much slower at pulling the image compared to how long docker-image
took.

---
Concourse 5.5.7
test-registry-image (0.8.2): passed
test-docker-image: passed
side-note: registry-image was faster at finishing compared to docker-image

---
Concourse 6.4.1
test-registry-image (with 0.8.2): failed
test-docker-image: passed
side-note: this older version of registry-image was finished faster compared to docker-image. It
appears registry-image got slower going from 0.8.2 -> 0.11.1

---
Concourse 5.5.7
test-registry-image (with 0.11.1): passed
test-registry-image (with 0.8.2): passed
test-docker-image: passed
```
