### ISSUE TITLE
Need to be able to specify a CA cert like docker-image resource

### ISSUE THREAD

**Issue by techgnosis** [concourse/registry-image-resource#240]
Concourse is awesome, thanks guys!

I can't migrate to registry-image because it doesn't let me specify a CA cert like docker-image. Specifying a CA cert is crucial for people who have on-prem registries.

docker-image looks like this..
```
- name: concourse-helper
  type: docker-image
  source:
    repository: ((harbor-domain))/library/concourse-helper
    tag: 1
    ca_certs:
    - domain: ((harbor-domain))
      cert: |
        ((ca_cert))
```

**Comment by crackcomm** [comment]
I found myself patching image and using my own also.

```Patch
diff --git a/dockerfiles/alpine/Dockerfile b/dockerfiles/alpine/Dockerfile
index e6e5bcd..77fdab3 100644
--- a/dockerfiles/alpine/Dockerfile
+++ b/dockerfiles/alpine/Dockerfile
@@ -23,6 +23,9 @@ RUN chmod +x /opt/resource/*
 # https://github.com/gliderlabs/docker-alpine/issues/367
 RUN echo "hosts: files dns" > /etc/nsswitch.conf
 
+COPY ca.pem /usr/local/share/ca-certificates/local-ca.crt
+RUN update-ca-certificates
+
 FROM resource AS tests
 COPY --from=builder /tests /tests
 ADD . /docker-image-resource
```


```yaml
resource_types:
- name: registry-image
  type: docker-image
  source:
    repository: crackcomm/registry-image-resource
```
