### ISSUE TITLE
Cannot add host

### ISSUE THREAD

**Issue by skreddy6673** [concourse/registry-image-resource#242]
Instead of adding the registry mirror to docker image in repository, i'm thinking to use registry_mirror and host that are defined in here https://github.com/concourse/registry-image-resource/#source-configuration/
#registry_mirror

```
jobs:
- name: job-hello-world
  plan:
  - config:
      container_limits: {}
      image_resource:
        source:
          repository: busybox
          registry_mirror:
            host: MIRROR_URL
        type: registry-image
      platform: linux
      run:
        args:
        - hello world
        path: echo
    task: hello-world
  public: true
```

When i ran this pipeline i'm getting 
```
resource script '/opt/resource/check []' failed: exit status 1

stderr:
[31mERRO[0m[0000] invalid payload: json: unknown field "registry_mirror" 
```
