### ISSUE TITLE
Testcafe not working, but works with docker-image

### ISSUE THREAD

**Issue by tenjaa** [concourse/registry-image-resource#250]
Hi,
we are in the process of migrating to the registry image resource and found one issue when running [testcafe](https://devexpress.github.io/testcafe/).
I created a minimal example, but have no idea how to go any further with it.
Can you maybe give a hint on where to look?

```yaml
jobs:
- name: works
  plan:
  - task: testcafe
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: testcafe/testcafe
      run:
        path: sh
        args:
        - -ec
        - |
          cd
          wget https://devexpress.github.io/testcafe/downloads/sample-test.zip
          unzip sample-test.zip
          sed -i 's/Peter/P.Parker/' test-example.js
          testcafe chromium:headless test-example.js
- name: works-not
  plan:
  - task: testcafe
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: testcafe/testcafe
      run:
        path: sh
        args:
        - -ec
        - |
          cd
          wget https://devexpress.github.io/testcafe/downloads/sample-test.zip
          unzip sample-test.zip
          sed -i 's/Peter/P.Parker/' test-example.js
          testcafe chromium:headless test-example.js
```
