### ISSUE TITLE
param version : invalid payload: json: unknown field "version" 

### ISSUE THREAD

**Issue by opicaud** [concourse/registry-image-resource#255]
This is my pipeline

resources:
  - name: source-code
    type: git
    source:
      uri: ((git-repo))
      private_key: ((git-private-key))
      forward_agent: true

  - name: registry
    type: registry-image
    icon: docker
    source:
      repository: ((image-repo-name))/my-product
      debug: true

jobs:
  - name: build
    plan:
      - get: source-code
        trigger: true
      - task: build-task-image
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: vito/oci-build-task
          inputs:
            - name: source-code
          outputs:
            - name: image
          run:
            path: build
          caches:
            - path: cache
          params:
            CONTEXT: source-code
      - put: registry
        params:
          image: image/image.tar
          version: 0.0.1

Out of pipeline : 
invalid payload: json: unknown field "version" 

Seems wired, the struct of PutParams has been updated with this.
Same with "variant" and "bump_aliases"

I've seen also that the image has been pushed 4 days ago, same that the last tag..
I suppose so the image has been updated with the last version of the code

Am I doing something wrong ?

**Comment by chenbh** [comment]
Each release of Concourse comes with a set of base resource types (git, registry-image, etc..) and those are fixed with each version (e.g. 6.7.0 shipped with registry-image 0.14.0). If you want to use the latest image, you'll have to declare it as a custom resource type.

```yaml
resource_types:
- name: registry-image # you can "redefine" base resource types like this
  type: registry-image # the workers must ship with a base registry-image resource, otherwise how would it fetch more images?
  source:
    repository: concourse/registry-image-resource
    tag: 1.0.0
```

**Comment by opicaud** [comment]
Oh yeah, that's was a question i had about this base resource type : how does it work to find the good version ?
Now i've got the answer, it's shipped with Concourse :)
Thanks for your help, it's working now.
FYI I tried this but with tag: latest and not tag:1.0.0 ... (and i did not make the link when i was into the docker hub, indeed i did not find any latest version tag...)
I've learnt something today thanks to you about the base registry-images!
Thanks !

**Comment by chris-aeviator** [comment]
@chenbh 

> 
```yaml
resource_types:
- name: registry-image # you can "redefine" base resource types like this
  type: registry-image # the workers must ship with a base registry-image resource, otherwise how would it fetch more images?
  source:
    repository: concourse/registry-image-resource
    tag: 1.0.0
```
>

I'm getting an `error: resource not found` whenever trying to add a pipeline with this added.
