### ISSUE TITLE
How to work with incremental versions (semver)

### ISSUE THREAD

**Issue by f0o** [concourse/registry-image-resource#256]
Hi,

I'm struggling to understand how this resource could work with the semver resource to push tagged/versioned images and also act as trigger for pipelines on new versions.

For example I'd like to build a docker image on git-commits and tag them according to semver where each build would bump the patch version.

Would the build pipeline look like this:
```
jobs:
  - get: source-code
    trigger: true
  - task: build
    ...
  - put: version
    params:
      bump: patch
  - put: image
    params:
      image: image/image.tar
      additional_tags: version/version (???)
```

And what about the trigger pipeline? How would the registry-image resource need to be configured to be triggered by above put?

**Comment by vito** [comment]
This should be addressed with v1.0 now that it supports semver tagging semantics (#214).

It works something like this:

```yaml
resources:
- name: my-image
  type: registry-image
  source: {repository: my-repo} # do not set 'tag'!

jobs:
- name: build-and-push
  plan:
  - get: source-code
    trigger: true
  - task: build
    # ...
  - put: version
    params:
      bump: patch
  - load_var: version
    file: version/version
  - put: image
    params:
      image: image/image.tar
      version: ((.:version))
      # if desired, bump '1', '1.2', and 'latest' as apropriate
      # bump_aliases: true
```

Note the addition of the `load_var` step, since version takes a literal value rather than a file path.
