### ISSUE TITLE
"put" step fails with error "not implemented"

### ISSUE THREAD

**Issue by OwenGr** [concourse/registry-image-resource#26]
Fairly basic pipeline, just builds an image:

```
jobs:
- name: build-image
  plan:
  - aggregate:
    - get: dockerfile
      trigger: true
  - task: build
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: {repository: concourse/builder}
      params:
        REPOSITORY: bdaimna20corecr01.azurecr.io/terraform/azuretfv
        TAG: latest
        CONTEXT: dockerfile/dockerfiles/azuretfv
      inputs: [{name: dockerfile}]
      outputs: [{name: image}]
      run: {path: build}
  - put: build-image
    params: {image: image/image.tar}

- name: build-image
  type: registry-image
  source:
    repository: bdaimna20corecr01.azurecr.io/terraform/azuretfv
    username: ((registry-username))
    password: ((registry-password))
```

On the put step, receiving the following in Concourse:
```
ERRO[0000] not implemented                              
```

Any ideas?
