### ISSUE TITLE
skip_download still downloads

### ISSUE THREAD

**Issue by mmb** [concourse/registry-image-resource#266]
I'd like to use this resource for triggering only. I am using this config but it still does the download:

```yaml
- get: image
  trigger: true
  get_params:
    skip_download: true
```

I first had it in `params:` but I got `ERRO[0000] invalid payload: json: unknown field "skip_download"`. If get_params is right it might be something to add to the README.
