### ISSUE TITLE
Layers that delete and then recreate a directory aren't unpacked properly

### ISSUE THREAD

**Issue by chenbh** [concourse/registry-image-resource#267]
## Steps to reproduce

1. Using the following Dockerfile to build and push an image
    ```Dockerfile
    FROM busybox
    RUN mkdir -p /foo/bar

    RUN rm -r /foo && mkdir -p /foo/baz
    ```
1. Try to use it in a task
    ```yaml
    jobs:
    - name: foo
      plan:
      - task: test
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: trasacom/foo
    
          run:
            path: sh
            args: ["-c", "ls /foo"]
    ```
## Expected results

It only prints 
```
baz
```

## Actual

```
bar  baz
```

## Additional info

This seems to be a bug related to removing and adding things in the same layer. Trying the steps above with the `RUN` split into 2 layers work as expected
```Dockerfile
FROM busybox
RUN mkdir -p /foo/bar

RUN rm -r /foo
RUN mkdir -p /foo/baz
```
