### ISSUE TITLE
Can't push to GCR using username / password

### ISSUE THREAD

**Issue by aholyoake-bc** [concourse/registry-image-resource#269]
We upgraded to concourse 7.1.0 yesterday (registry-image-resource 1.2.0) and we are now having problems with pipelines using the `registry-image` resource to push to a private google container registry.

The credentials are still working fine for any pipelines still using the `docker-image` resource.

Pipeline resource definition:
```
- icon: docker
  name: service-image
  source:
    password: ((docker-credentials))
    repository: eu.gcr.io/XXX-project-XXX/service-image
    username: _json_key
  type: registry-image
```

Error message:
```
ERRO[0003] pushing image failed: pushing tag(s): PATCH https://eu.gcr.io/v2/XXX-project-XXX/service-image/blobs/uploads/AJAD5v0TaF8_kTQx2bOCfvnSIcxKmqfK5U2dQ88-om9B-uIlbF3aGYvJVzQ30qEcf86vftNWMpGEQFQ6bJGVGpQ: DENIED: Access denied.
```

I've manually added the rootfs / resource_manifest to our concourse workers for v1.0.0 and everything works as expected
