### ISSUE TITLE
Error when using `bump_aliases: true` for first image push

### ISSUE THREAD

**Issue by pn-santos** [concourse/registry-image-resource#281]
I think I found an issue when using `bump_aliases: true` for images that do not yet exist in the repository.

### Scenario

**Given** a semver-based (no tag) `registry-image` resource, e.g.:
```yaml
  - name: jre.oci
    type: registry-image
    icon: docker
    source:
      repository: my.repo.com/runtime/jre
    check_every: never
```

**And** Image in question doesn't yet exist in the repo

**When** a `put` specifying `bump_aliases` is done:
```yaml
- put: jre.oci
  inputs: detect
  params:
    image: image/image.tar
    version: ((.:image-version))
    bump_aliases: true
  get_params:
     skip_download: true
```

**Then** the image should be pushed with `latest` and all `M`, `M.m` and `M.m.p` versions

### What actually happens

The `put` step logs this error:
```
ERRO[0000] determine aliases: list repository tags: GET https://my.repo.com/v2/runtime/jre/tags/list?n=1000: NAME_UNKNOWN: repository name not known to registry; map[name:runtime/jre]
```

I tried manually pushing the image and re-running the job and then it worked correctly.

### Versions

- Concourse v7.2.0
- `registry-image` resource that was bundled with v7.2.0
