### ISSUE TITLE
Can't fetch image via specific tag

### ISSUE THREAD

**Issue by EclipseTech** [concourse/registry-image-resource#292]
Feature Request: 
Fetch (in:) to allow param tag

Issue: The tag for the registry-image resource is in a git repository and not available at time of defining registry-image resource

Examples:
```
  - get: image
    params:
      format: oci
      # Option 1
      tag: ((.:version-tag))
      # Option 2
      tag_file: repo/.git/ref
```
I currently can't specify this version-tag / ref in resource definition as I don't have access until repo is cloned during the job

I'm not great with go, so here is something like what I'm thinking:

```
diff --git a/commands/in.go b/commands/in.go
index cbffa4e..8e2a16f 100644
--- a/commands/in.go
+++ b/commands/in.go
@@ -76,7 +76,12 @@ func (i *In) Execute() error {
                return fmt.Errorf("failed to resolve repository: %w", err)
        }

-       tag := repo.Tag(req.Version.Tag)
+       var tag name.Tag
+       if req.Params.Tag != "" {
+               tag = repo.Tag(req.Params.Tag)
+       } else {
+               tag = repo.Tag(req.Version.Tag)
+       }

        if !req.Params.SkipDownload {
                mirrorSource, hasMirror, err := req.Source.Mirror()
diff --git a/types.go b/types.go
index 9f77514..a2071b4 100644
--- a/types.go
+++ b/types.go
@@ -379,6 +379,7 @@ type MetadataField struct {
 type GetParams struct {
        RawFormat    string `json:"format"`
        SkipDownload bool   `json:"skip_download"`
+       Tag          string `json:"tag"`
 }
```
Reason I'm not submitting a code request at the moment is I'm hoping there is either a way around this that I'm not seeing.  Also I can't find contribution documentation explaining how to test.

**Comment by sandipndev** [comment]
Did you find a solution to this problem?
I'm facing this too!

**Comment by taylorsilva** [comment]
This use case would break the resource interface that concourse lays out. This comment applies to the PR #326 as well.

What would happen if that PR was accepted is you would have the resource's `check` step saying it's fetching the `latest` tag and then the `get` step downloading a completely different tag. This breaks the resource contract in concourse.

For a use case like this I tend to go for making a task to do the fetching. I'd probably use [podman](https://github.com/containers/podman) and write a script that would download and save the image as an OCI tarball or rootfs format. There are steps here on how to save a container image to the rootfs format: https://concourse-ci.org/concourse-worker.html#installing-or-upgrading-bundled-resource-types (replace `docker` with `podman` and existing commands should work fine)

psuedo-code of said script, not sure if `sh` is in the podman container:

```yaml
---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: quay.io/podman/stable
    tag: 'latest'

params:
  USERNAME: ((username))
  PASSWORD: ((password))
  REGISTRY: // registry domain
  IMAGE: // image name, like podman/hello or library/golang, etc.
  TAG: ((tag))

outputs:
- name: image

run:
  path: sh
  args:
  - -exc
  - |
    podman login --username "$USERNAME" --password "$PASSWORD" $REGISTRY
    podman pull "${REGISTRY}/${IMAGE}:${TAG}"
    podman save --format oci-archive > output/image.tar
```

For the above reason I'm going to close this issue and the related PR. Leave another comment if further explanation about the workaround is needed.
