### ISSUE TITLE
version parameter removes '0' in certain situations

### ISSUE THREAD

**Issue by Zeigren** [concourse/registry-image-resource#293]
I'm using the version parameter to set a tag but instead of say '21.05.3' it'll tag the image '21.5.3'. This doesn't effect something like '0.7.5' though.

Example snippet:

```
- put: dockerhub-image
  params:
    image: image/image.tar
    version: 21.05.3
```
[yml file](https://github.com/Zeigren/bookstack_docker/blob/main/concourse-ci.yml)
[Example job](https://concourse.kairohm.dev/teams/main/pipelines/bookstack/jobs/build-and-push/builds/4)

Note: Even though I'm using `load_var` in the yml file I linked the behavior is the same when it's set manually like in the example snippet.
