### ISSUE TITLE
insecure not working for https registry

### ISSUE THREAD

**Issue by wlwwu** [concourse/registry-image-resource#304]
err information:

ERRO[0004] pushing image failed: initialize transport: GET http://xxxxxx/v2/: unexpected status code 400 Bad Request: <html>

<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>

<body>

<center><h1>400 Bad Request</h1></center>

<center>The plain HTTP request was sent to HTTPS port</center>

<hr><center>nginx/1.19.1</center>

</body>

 /html>

pipeline:
resource_types:
- name: registry-image-custom
  type: registry-image
  source: {repository: cherwin/registry-image-resource}

resources:
- name:  xxxxx
  type: git
  icon: github-circle
  source:
    uri: ((xxxxurl))
    branch: ((xxxxx-branch))
    private_key: ((xxxxxey))
    skip_ssl_verification: true

# Where we will push the image
- name: ruby-image
  type: registry-image-custom
  icon: docker
  source:
    repository: xxxxxxx
    tag: latest
    username: ((REGISTRY_USERNAME))
    password: ((REGISTRY_PASSWORD))
    insecure: true

Just want to know how to set the insecure flag here

**Comment by chris-aeviator** [comment]
this is to be expected, a HTTPS connection can not be used with HTTP

**Comment by cherwin** [comment]
Try something like below

```yaml
resource_types:
  - name: registry-image-insecure
    type: docker-image
    source:
      repository: cherwin/registry-image-resource
      tag: 0.1.0

resources:
- name: git-repository
  type: git
  icon: github
  source:
    uri: ((uri))
    branch: master

- name: docker-registry
  type: registry-image-insecure
  icon: docker
  source:
    repository: my.private.insecure.registry:5000/foo
    insecure: true
```
