### ISSUE TITLE
invalid payload: json: unknown field "insecure" 

### ISSUE THREAD

**Issue by chris-aeviator** [concourse/registry-image-resource#310]
When trying to connect to a `http` only registry, according to the readme I'm supposed to add `insecure: true` to the source configuration.

However, when pushing an image, the build fails with 

 ```
ERRO[0000] invalid payload: json: unknown field "insecure" 

```

![image](https://user-images.githubusercontent.com/11522213/147609555-654073f2-344c-4291-9014-6fc1d39fe0d0.png)

```
❯ cat build-agent.yml
resources:
- name: prefect-agent
  type: git
  icon: github
  source:

    uri: http://git.sentinel.loc/chris/alpine-ci-dockerbuild-tester
    branch: master
    username: ##############
    password :################
    skip_ssl_verification: true

# Where we will push the image
- name: docker-registry
  type: registry-image
  icon: docker
  source:
    repository: ((image-repo-name))/alpine-ci-test
    tag: latest
    insecure: true

jobs:
- name: build-and-push
  plan:
  - get: prefect-agent
    trigger: true
  - task: build-task-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: prefect-agent
      outputs:
      - name: image
      params:
        CONTEXT: prefect-agent/Dockerfiles
      run:
        path: build
  - put: docker-registry
    params:
      image: image/image.tar
```

```
fly -t sent-loc set-pipeline -p build-and-push-agent-image \
  -c ./build-agent.yml \
  --var image-repo-name=http://docker.sent.loc
```

Version 7.6.0
