### ISSUE TITLE
Prerelease builds not picked up

### ISSUE THREAD

**Issue by kkavitha** [concourse/registry-image-resource#330]
Hi, I am using the latest version of registry-image-resource.
My resource definition is as follows:
```
- name: my-image
  type: registry-image
  icon: docker
  source:
    repository: <>
    username: <>
    password: <>
    semver_constraint: ">=1.2.1-0"
```
I was expecting to see `1.2.1-beta.1` version pop up in my resource list, but I dont see it. 
Is there a mistake in the way I have specified the semver_constraint?

Thank you!
