### ISSUE TITLE
edge tag of Alpine is used by default

### ISSUE THREAD

**Issue by link2xt** [concourse/registry-image-resource#338]
The readme says that `latest` tag is used by default. However, I have to configure Alpine image like this:
```
      image_resource:
        name: ""
        source:
          repository: alpine
          tag: latest
        type: registry-image
```

If I remove the `tag`, it uses the `edge` tag of https://hub.docker.com/_/alpine instead.
