### ISSUE TITLE
put version only allows semver

### ISSUE THREAD

**Issue by ianatarewe** [concourse/registry-image-resource#362]
### Describe the bug

What if this image represents an internal application with continuous delivery and not a released application for self-hosting?

There is no valid reason why we should need to maintain semver versions if our actual versioning is linear and modeled as a series of deployments of a candidate to stages.

### Reproduction steps

1. try to put to a registry-image with version "prod"

### Expected behavior

it pushes the revision to the tag "prod", but instead it complains it isn't semver.

**Comment by ianatarewe** [comment]
Note, there is a workaround which is to push a file into an output with the desired tag and use additional_tags, but why is that required?

**Comment by taylorsilva** [comment]
I'm confused by what you're asking for. To me, it _sounds_ like you would use the `tag` field and set it to `prod` in your example.

```yaml
resources:
- name: my-image
  type: registry-image
  source:
    repository: my-registry.com/org/my-image
    tag: prod

jobs:
- name: my-job
  plan:
  //...some other steps to build an image
  - put: my-image
    params:
      image: some-output/image.tar
```

If the tag varies for each push then you could also do this:

```yaml
resources:
- name: my-image
  type: registry-image
  source:
    repository: my-registry.com/org/my-image
    // maybe use tag_regex, but not required for this case

jobs:
- name: my-job
  plan:
  //...some other steps to build an image
  - put: my-image
    params:
      image: some-output/image.tar
      additional_tags: some-file/with-tags
```

Based on my reading of the docs I think either of those should work for you. Of course I don't have your full context so I might be missing something here.
