### ISSUE TITLE
Failed to pull/push image from quay registry

### ISSUE THREAD

**Issue by insider89** [concourse/registry-image-resource#38]
I have the following error when trying to pull image from quay repository:
`ERRO[0000] failed to extract image: MANIFEST_UNKNOWN: "manifest unknown" `

**How to reproduce?**
Simple pipeline:
```
---
jobs:
- name: my-test-job
  serial: true
  plan:
  - get: hyperkube-build-image


resources:
- name: hyperkube-build-image
  type: registry-image
  source:
    repository: quay.io:443/coreos/hyperkube
    tag: v1.9.6_coreos.2
  check_every: 60m
```

Here is what *docker manifest* command return:
```
> docker manifest inspect quay.io:443/coreos/hyperkube:v1.9.6_coreos.2
unsupported manifest media type and no default available: application/vnd.docker.distribution.manifest.v1+prettyjws
```

Can you please add the ability to pull/push image from/to quay registry?
