### ISSUE TITLE
Example usage

### ISSUE THREAD

**Issue by artsyca** [concourse/registry-image-resource#40]
Reading through the issues and documentation it seems this is a very idiomatic plugin for concourse but I can't configure it to work with concourse/builder-task --

I have an output from builder-task which is an `image.tar` file I want to upload to my registry on docker hub; is there an example task I can refer to for doing this?

**Comment by artsyca** [comment]
Answer to my own question, would this be accurate? in `pipeline.yml`

```
resource_types:
- name: registry-image
  type: docker-image
  source:
    repository: concourse/registry-image-resource
    tag: latest

resources:
- name: my-docker-registry
  type: registry-image
  source:
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    repository: ((docker-hub-repository))

... more resources

jobs:
  plan:

    - ... get stuff
    - ... do stuff

    - task: docker-build
      privileged: true
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: concourse/builder-task
        params:
          REPOSITORY: concourse/builder-task
          TAG: latest
          DOCKERFILE: path/to/Dockerfile
        inputs:
          - name: dist
          - name: etc
        outputs:
          - name: image
        caches:
          - path: cache
        run:
          user: root
          path: build

     - put: my-docker-registry
       params:
         image: image/image.tar
```
