### ISSUE TITLE
Feature request: support digest in 'source'

### ISSUE THREAD

**Issue by johha** [concourse/registry-image-resource#45]
Hi,
we'd like to specify a digest instead of a tag in the source section of a registry-image resource. This would make it easier for us to ensure that our jobs are using the correct version of our images because tags can be changed easily and only the digest is really unique.

I know that there is [resource pinning](https://github.com/concourse/concourse/issues/2439) available in Concourse v5 but it's not really the same thing.
E.g. if I provide a wrong digest (no image available for that digest) the pinning causes the job to wait forever until a resource with this digest is available. Instead I would like to have a failing resource with some error message (e.g. digest not found).

As a digest is an alternate way to get a specific version of an image I think the right place to specify it would be in source section:
```
resources:
- name: my-image
  type: registry-image
  source:
    repository: myrepo/my-image
    digest: sha256:a252b563fad36e16b71c0aab7d1ea8e380c6a4b21d69d6d38efa4cd873e8da09
```

What do you think about this?

**Comment by vito** [comment]
Hmm it seems like we should instead fix/improve the UX of version pinning in Concourse. I don't want every resource author to have to implement pinning themselves. Would you mind opening a feature request for that instead? Thanks!

**Comment by jchesterpivotal** [comment]
In the example:

```
resources:
- name: my-image
  type: registry-image
  source:
    repository: myrepo/my-image
    digest: sha256:a252b563fad36e16b71c0aab7d1ea8e380c6a4b21d69d6d38efa4cd873e8da09
```

Does `myrepo/my-image@sha256:a252b563fad36e16b71c0aab7d1ea8e380c6a4b21d69d6d38efa4cd873e8da09` not work?

**Comment by vito** [comment]
@jchesterpivotal That won't work since the resource doesn't respect a `digest:` field under `source:`, but this should work:

```yaml
resources:
- name: my-image
  type: registry-image
  source:
    repository: myrepo/my-image
  version:
    digest: sha256:a252b563fad36e16b71c0aab7d1ea8e380c6a4b21d69d6d38efa4cd873e8da09
```

...as well as this (in a task config):

```yaml
image_resource:
  type: registry-image
  source:
    repository: myrepo/my-image
  version:
    digest: sha256:a252b563fad36e16b71c0aab7d1ea8e380c6a4b21d69d6d38efa4cd873e8da09
```
