### ISSUE TITLE
Ability to use semver version for tag

### ISSUE THREAD

**Issue by roshankadasani** [concourse/registry-image-resource#48]
When using `additional_tags` option in the `put` params, the resource tags and pushes the images with the ones specified in the additional tags file and also the `tag` specified in resources' source. I am using [semver concourse resource](https://github.com/concourse/semver-resource) for versioning tags and I want to push just the tag specified in the file. Or is there a way I can pass my servem verion to the `tag` in the sources?

Resource
```yaml
- name: docker-image
  type: registry-image
  source:
    repository: {{REPO_NAME}}
    username: ((username))
    password: ((password))
    tag: ##<servem-verion-file>##
```

Job
```yaml
- put: docker-image
    params: 
      image: image/image.tar
      additional_tags: version/number
```

If passing the servem version to the `tag` is not possible can we use something similar to `tag_file` in the [docker image resource](https://github.com/concourse/docker-image-resource#out-push-an-image-or-build-and-push-a-dockerfile)?
