### ISSUE TITLE
Failed to pull specific image from Docker Hub

### ISSUE THREAD

**Issue by Zerpet** [concourse/registry-image-resource#56]
We found an issue with registry image where an image available in Docker Hub and `docker pull`able failed in the `get` step of a job.

The image failing in the `get` step is from RabbitMQ Docker Hub:

```
rabbitmq@sha256:7c592e6c6b3510fa4353fa078ee3d5bd0b0ea5500ddee31607b964f02d0b46e2
```

This is how our resource definition and job is configured:

```
- name: rabbitmq-release
  type: registry-image
  source:
    repository: rabbitmq
    tag: 3.8-rc-management
  version: {digest: "sha256:7c592e6c6b3510fa4353fa078ee3d5bd0b0ea5500ddee31607b964f02d0b46e2"}

- name: some-job
  plan:
  - get: rabbitmq-release
    params:
      format: oci
[...]
```

In the `get` step, we get the following error message:

```
fetching rabbitmq@sha256:7c592e6c6b3510fa4353fa078ee3d5bd0b0ea5500ddee31607b964f02d0b46e2
ERRO[0000] failed to write OCI image: unsupported status code 404; body: 404 page not found 
```

However, we are able to `docker pull` this image. Worth mentioning, this image has another SHA `rabbitmq@sha256:76346c31d3eee20f82ebc2573cb0be891e4827b35e875f53cc93c9df76143732` that is `docker pull`able and it works fine with the registry image resource.
