### ISSUE TITLE
Ability to add full description from README.md in Docker Hub

### ISSUE THREAD

**Issue by tremblaysimon** [concourse/registry-image-resource#78]
It would be nice to add a `description` out parameter to be able to add a full description in Docker Hub from a README.md file (usually from the git repository that contains the Dockerfile used to build the image). 

It could be something like this: 

```
  - put: docker-hub
    params:
      image: image/my-beautiful-image.tar
      description: repo/README.md
```

Of course that feature would only works with Docker Hub repository.

 For us it would be nice because we want to be on par between an image description from Docker Hub and the GitHub repository that contains the files used to build that image.

Does it sound a good idea?
